version: '3.1'
services:
  api:
    image: ghcr.io/pierregillon/bootstrap.api:sha-22ae46d
    container_name: bootstrap.api
    environment:
        Database__Host: host.docker.internal
        Database__Port: 5432
        Database__Database: postgres
        Database__User: postgres
        Database__Password: P@ssw0rd!
        IS_SWAGGER_ENABLED: true
    ports:
      - "5000:80"
    networks:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: bootstrap.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: bootstrap.pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: P@ssw0rd!
        PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - db
    depends_on:
      - db
      
networks:
  db: