name: .NET

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pierregillon/bootstrap.web.api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/Bootstrap.WebApi.sln
      - name: Build
        run: dotnet build ./src/Bootstrap.WebApi.sln --no-restore
      - name: Test
        run: dotnet test ./src/Bootstrap.WebApi.sln --no-build --verbosity normal

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build_and_tests
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}